# Generated by Django 4.1.3 on 2022-11-10 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_read_num_readnum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
